---
- name: HARDEN IOS ROUTERS
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: ENSURE THAT ROUTERS ARE SECURE
      ios_config:
        src: 32-secure-config.cfg
...